#!/bin/bash

IPT="/sbin/iptables"

$IPT -F
$IPT -X
$IPT -P INPUT DROP
$IPT -P FORWARD DROP
$IPT -P OUTPUT DROP

# Accept all established connection (3 way handshake)
$IPT -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
$IPT -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Authorize loopback
$IPT -A INPUT -i lo -j ACCEPT
$IPT -A OUTPUT -o lo -j ACCEPT

# Allow incoming and outgoing ping
$IPT -A INPUT -p icmp --icmp-type 8 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
$IPT -A OUTPUT -p icmp --icmp-type 8 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

# Allow FTP incoming and outgoing connections
$IPT -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
$IPT -A OUTPUT -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A OUTPUT -p tcp --dport 53 -m state --state NEW -j ACCEPT
$IPT -A OUTPUT -p udp --dport 53 -m state --state NEW -j ACCEPT

# Allow SSH connection
$IPT -A INPUT -p tcp -m state --state NEW --dport 2222 -j ACCEPT

# Block furtive port scanning
$IPT -N port-scan
$IPT -A port-scan -j LOG --log-level 4 --log-prefix 'Blocked_scans'
$IPT -A port-scan -j DROP
iptables -N UDP
iptables -A UDP -j LOG --log-level 4 --log-prefix 'UDP_FLOOD '
iptables -A UDP -p udp -m state --state NEW -m recent --set --name UDP_FLOOD
iptables -A UDP -j DROP
iptables -A INPUT -m recent --name port-scan --rcheck --seconds 86400 -j port-scan
iptables -A INPUT -m recent --name UDP_FLOOD --rcheck --seconds 86400 -j port-scan
iptables -A INPUT -m recent --name port-scan --remove
iptables -A INPUT -m recent --name UDP_FLOOD --remove
